# Generated by Django 4.0.6 on 2022-07-22 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='title',
            new_name='listing_title',
        ),
    ]
