# Generated by Django 4.0.6 on 2022-07-22 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_title_listing_listing_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_title',
            field=models.CharField(max_length=100),
        ),
    ]
