# Generated by Django 4.0.6 on 2022-07-22 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='category',
            new_name='listing_category',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='listing_id',
        ),
        migrations.AddField(
            model_name='bid',
            name='bid_listing_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bid_listing_id', to='auctions.listing'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=75)),
                ('comment_listing_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_listing_id', to='auctions.listing')),
                ('commenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commenter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='auctions.listing')),
                ('category_listing_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_listing_id', to='auctions.listing')),
            ],
        ),
    ]
