# Generated by Django 4.0.6 on 2022-07-22 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_rename_category_listing_listing_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='listing_category',
            new_name='category',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
