# Generated by Django 4.0.6 on 2022-07-22 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_rename_comments_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bid_listing_id',
            new_name='listing',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='bidder',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_listing_id',
            new_name='listing',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='commenter',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='listing_owner',
            new_name='user',
        ),
    ]
